name: mymedia
project: default
export_path: /var/backup/mymedia
services:
    mydb:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: testapp.yaml
        depends_on:
            - cloudytwo
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/backup/tank/media
                target: /media
                shift: true
    myapp:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: testapp.yaml
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/backup/tank/media
                target: /media
                shift: true
profiles:
    - default
    - vlan5
