name: testapp
project: testproject
services:
    dbservice:
        image: docker:postgres
        volumes:
            data:
                mountpoint: /data
                pool: fast
                snapshot:
                    schedule: '@hourly'
                    expiry: 7d
    testservice:
        image: images:ubuntu/noble/cloud
        volumes:
            metadatavolume:
                mountpoint: /metadata
                pool: slowpool
        binds:
            mediabind:
                type: disk
                source: /mnt/media
                target: /media
                shift: true
        additional_profiles:
            - profile2
        cloud_init_user_data_file: testapp.yaml
        snapshot:
            schedule: '@daily'
            expiry: 14d
        depends_on:
            - dbservice
profiles:
    - default
    - profile1
