name: dependencies
project: default
export_path: /var/backup/mymedia
services:
    myjellyfin:
        image: docker:jellyfin/jellyfin
        environment_file: myjellyfin.env
        gpu: true
        volumes:
            config:
                mountpoint: /config
                pool: default
                snapshot:
                    schedule: "0 0 * * *"
                    expiry: 2w
        binds:
            media:
                type: disk
                source: /var/backup/tank/media
                target: /media
                shift: true
    cloudyone:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: testapp.yaml
        depends_on:
            - myjellyfin
            - cloudytwo
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/backup/tank/media
                target: /media
                shift: true
    cloudytwo:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: testapp.yaml
        depends_on:
            - myjellyfin
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/backup/tank/media
                target: /media
                shift: true
profiles:
    - default
    - vlan5
